### ISSUE TITLE
Tips to Speed up Simulations?

### ISSUE THREAD

**Issue by jeevster** [torchmd/torchmd-protein-thermodynamics#11]
I am trying to run simulations with the trained NNPs, and for the larger proteins (e.g alpha-3d) I observe a speed of around 10-12 timesteps per second of GPU time (with 32 replicas). With a timestep of 1 fs and a total time of ~5-10 ns depending on the protein, this would translate to several days of GPU time to perform one complete simulation.

I'm simulating on a single NVIDIA RTX A6000. I did some quick profiling and noticed that the calculation of the classical/prior force terms are dominating the runtime. I also noticed my GPU utilization is pretty low (~10%). Do you have any tips for speeding up the simulations?

Thanks!

**Comment by stefdoerr** [comment]
Hi @jeevster , what priors are you using?

**Comment by stefdoerr** [comment]
@poroussong you are probably using the wrong conda enviroment when starting your interpreter (ipython, notebook, python)

**Comment by jeevster** [comment]
@stefdoerr I am using the default priors given in the simulate.yaml file: Bonds, RepulsionCG, and Dihedrals. I've attached a screenshot of the config file.
![image](https://github.com/torchmd/torchmd-protein-thermodynamics/assets/71562492/cd16076b-f326-43dd-8b9f-b38b92f4453f)

**Comment by jeevster** [comment]
Just following up. Any thoughts on this?

**Comment by jeevster** [comment]
Hi, just wanted to follow up again regarding this. I would greatly appreciate a response/pointers in the right direction, thanks!

**Comment by jeevster** [comment]
Ok, thanks I will take a look at OpenMM. In the meantime, would you mind sharing a ballpark estimate of the simulation speed you achieved using TorchMD for the results reported in the "Machine learning coarse-grained potentials of protein thermodynamics" paper (e.g for a protein-specific model and for the general all-protein model)? This information would be helpful to gauge whether I am limited by the slowness of TorchMD, or some other issue (e.g hardware, as you suggested). Thanks

**Comment by AdriaPerezCulubret** [comment]
If I recall correctly, it took us 5 days ~ 1 week to simulate "6ns" on a3D using TorchMD, using 32 replicas. Can't find exact simulation speed.

For a more exact estimate, check the speed comparison available in the TorchMD publication.

**Comment by jeevster** [comment]
I see, thanks. I also noticed there is an "optimized" version of the TorchMD_GN model at torchmd-net/torchmdnet/optimize.py. Is this a drop-in replacement for the base TorchMD_GN model defined in torchmd-net/torchmdnet/models/torchmd_gn.py ? And would you expect this model to be faster?

**Comment by AdriaPerezCulubret** [comment]
Not sure about that. I can't tell you now if it would optimize inference (and therefore simulation speed) or just training. Try asking in TorchMD-net repository.

**Comment by AdriaPerezCulubret** [comment]
Not sure about that. I can't tell you now if it would optimize inference (and therefore simulation speed) or just training. Try asking in TorchMD-net repository.
