### ISSUE TITLE
Refernece MD data

### ISSUE THREAD

**Issue by MaciejMajew** [torchmd/torchmd-protein-thermodynamics#12]
Reference MD simulations contain only xtc and no reference topology file. I checked trpcage, maybe others have it. 
@AdriaPerezCulubret can you add generators somewhere?

**Comment by AdriaPerezCulubret** [comment]
Uploaded trpcage with topologies (`filtered.psf` and `filtered.pdb`)

**Comment by AdriaPerezCulubret** [comment]
Uploaded trpcage with topologies (filtered.psf and filtered.pdb)

**Comment by ynshen** [comment]
Hi @AdriaPerezCulubret, thanks for sharing this awesome work! I just downloaded the reference MD data but found several trajectories missing topology files. Could you share these topology files or how to generate them? Thanks!

Here are trajectories missing topology files:
- a3D_1/a3D_2
- bba
- lambda
- ntl9
- proteing_2 (but proteing_1 has)
- wwdomain_1/wwdomain_2

**Comment by AdriaPerezCulubret** [comment]
I've updated the .tar.gz files for all reference trajectories mentioned, now they include the topology files.

Let me know if I'm missing any.
