### ISSUE TITLE
Missing files/error in Reference Markov state model simulation analysis

### ISSUE THREAD

**Issue by mjag1898** [torchmd/torchmd-protein-thermodynamics#15]
When I untar the file with precalculated all-atom MSMs (reference_MSM_analysis.tar.gz, at [this link](http://pub.htmd.org/protein_thermodynamics_data/reference_MSM_analysis.tar.gz) found in the Github), I get an error and the expanded directory is missing MSM files for three proteins (a3d, villin, wwdomain). 

Do you have a fix for this error or know where the missing MSM files can be found?

Error message below:

x reference_MSM/proteing_model_lag10ns_1200k_4ticadim_CAdist_skip1.dat: truncated gzip input
tar: Error exit delayed from previous errors.

**Comment by v-shaoningli** [comment]
same errors happened

**Comment by v-shaoningli** [comment]
Hi! There seems to be a permission issue. Could you please check into it? Thanks.
<img width="882" alt="image" src="https://github.com/torchmd/torchmd-protein-thermodynamics/assets/108473158/100ab9aa-ba4f-4ce3-9ff5-f8abdb649029">

**Comment by AdriaPerezCulubret** [comment]
Yes, sorry! Should be fixed now
