### ISSUE TITLE
Inquiry on Reproducing Min RMSD Results for Homeodomain with Provided Trajectories and Reference Structures

### ISSUE THREAD

**Issue by XJTUNR** [torchmd/torchmd-protein-thermodynamics#18]
I am writing to seek your guidance regarding an issue I have encountered while attempting to reproduce the minimum RMSD results for the homeodomain as presented in your paper.

I have developed a code that I have successfully used to replicate the results you reported for both chignolin and trpcage, which leads me to believe that the method I am employing is sound. However, when I apply the same code to the homeodomain data using the trajectories and reference structures you provided, the minimum RMSD results I obtain are not consistent with those reported in your article.

Before reaching out to you, I have taken the following steps to ensure the accuracy of my results:
1. Double-checked the provided trajectories and reference structures for any discrepancies.
2. Conducted multiple trials to confirm the reproducibility of my findings.

Given the discrepancy, I am curious if there might be a difference between the reference structures used in your study and those provided or if there might be an aspect of the computational method that I have overlooked.

I highly value the quality and impact of your research, and it is of great importance to me to accurately interpret and replicate your findings. I would greatly appreciate it if you could provide any insights or suggestions that might help me resolve this issue. Here is my code and the result (Reference MD: 0.56 vs 0.3; CG MD: 2.17 vs 1.8)

<img width="739" alt="image" src="https://github.com/torchmd/torchmd-protein-thermodynamics/assets/52536919/0acf9a5e-bc18-4bb8-aad9-23514dc05519">

Thank you for your time and consideration. I eagerly await your response and any assistance you might be able to offer.

Warm regards,
Yusong Wang

**Comment by AdriaPerezCulubret** [comment]
Thanks for your kind comments!

I've been checking, and we used a specific selection for homeodomain RMSD, because, if I recall correctly, it has a flexible tail that's never really folded. Selection used was `protein and name CA and resid 9 to 51`. Try that one and see if you can reproduce it now.

**Comment by XJTUNR** [comment]
Thank you for the detailed selection! 

After applying the specified selection of protein and name CA and resid 9 to 51, I am now able to precisely reproduce the results. The clarification on the flexible tail within the homeodomain RMSD was particularly helpful. 

I will close this issue. Thank you once again!
