### ISSUE TITLE
Question: Do you think we can use it for ddG prediction?

### ISSUE THREAD

**Issue by luwei0917** [torchmd/torchmd-protein-thermodynamics#2]
Interesting work.
If possible, could you provide an example for computing the energy of any given pdb structure using the learned potential? Thanks.

Wei

**Comment by giadefa** [comment]
HI, 
have you looked at the notebooks?

**Comment by luwei0917** [comment]
I misunderstood the paper. I was thinking there is a general potential that could predict the energy for any protein. But after taking a look of the tutorial and Dataset files, I realize its a protein-specific potential used to accelerate sampling.
I close this issues. if my current understanding is wrong, please correct me.
Thanks.
