### ISSUE TITLE
Duplicate bond entries with different parameters in prior force field

### ISSUE THREAD

**Issue by eva-not** [torchmd/torchmd-protein-thermodynamics#21]
In the prior_force_field.yaml file, there are duplicate bond entries, e.g. (CAA, CAC) and (CAC, CAA), with different parameters k0 and req. Why were different parameters fitted on what should be the same bond? Is this to preserve the N->C direction in a protein chain?

**Comment by MaciejMajew** [comment]
Hi! 
These are coarse grained bonds between CA beads that are not symmetric. this pseudobond would be CA-N-C-CA so it could have different parameters than CA-C-N-CA. Proline is a great example here. 
This also preserves some info about N->C direction.
Hope this helps.

**Comment by eva-not** [comment]
Thanks, this makes sense.
