### ISSUE TITLE
Question about Force Mapping for CG force

### ISSUE THREAD

**Issue by Jingdan-Chen** [torchmd/torchmd-protein-thermodynamics#23]
Hi! I would like to know your method for CG force(delta force) mapping from All-Atom ones(force), since I notice there exists high-level of flexibility in the methodology. I did not find related information in published manuscript or SI. Thank you!

**Comment by AdriaPerezCulubret** [comment]
Not sure I get your question. From the forces coming from all-atom MD simulations, we extracted only forces for CA atoms, and substracted the prior forces to obtain the set of delta-forces that we used to train the models.
