### ISSUE TITLE
Dataset Links not functional

### ISSUE THREAD

**Issue by mrjoness** [torchmd/torchmd-protein-thermodynamics#3]
Hello, This may still be under construction, but I wanted to report that none of the Dataset links lead anywhere at the moment.  I'm seeing the following error:

The 'torchmd/torchmd-protein-thermodynamics' repository doesn't contain the 'Datasets/pub.htmd.org/protein_thermodynamics_data/reference_trajectories/chignolin_trajectories.tar.gz' path in 'main'.  

Thank you.

**Comment by giadefa** [comment]
Sorry, missing http://.

it should be fixed now.

**Comment by mrjoness** [comment]
Thank you!
