### ISSUE TITLE
Permission denied when downloading .npy files

### ISSUE THREAD

**Issue by giacomo-janson** [torchmd/torchmd-protein-thermodynamics#4]
Hello,

thank you very much for sharing the code and data for such an interesting project.
I am trying to download alpha-carbon xyz coordinates files (the ones stored in npy files) from links provided in Datasets/README.md, but for some proteins there is a "Forbidden, you don't have permission to access" error. Specifically, I get this error for files:

villin_ca_coords.npy
ntl9_ca_coords.npy
bbl_ca_coords.npy
proteinb_ca_coords.npy
homeodomain_ca_coords.npy
proteing_ca_coords.npy
a3d_ca_coords.npy

while the download works for the remaining proteins. I also noticed the same error for npy files storing other features (e.g.: forces), but did not explore this in detail. Would it be possible to change permissions on the server to allow downloads?
Thanks

Giacomo

**Comment by AdriaPerezCulubret** [comment]
Hi!

Fixed the permissions, you should be able to download everything now.

**Comment by giacomo-janson** [comment]
They work now, thank you! Only one more small issue: in the README.md file, the links for the Coordinates, Forces and Deltaforces datasets of ntl9 seem to be incorrect. I think that the file names on the server are different from those in README.md.

**Comment by AdriaPerezCulubret** [comment]
Indeed they were wrong, should be fixed now. Many thanks!

**Comment by giacomo-janson** [comment]
Thank you for the fix! Everything works now.
