### ISSUE TITLE
How to build a  CG-NNP when the system contains two different proteins?

### ISSUE THREAD

**Issue by daniel1991zy** [torchmd/torchmd-protein-thermodynamics#7]
In my sumlutions, there are two kinds of peptides, named peptide-A and peptide-B. The number for each peptide is ten, and was solvated in water. So, the simulation box is consisted of ten pieces of peptide-A, ten pieces of peptide-B and a lot of water molecules. The cluster strcure of peptides is my focus, which can be simulted by TorchMD with a NNP potential ?

**Comment by MaciejMajew** [comment]
Hi. Generally, TorchMD can simulate the system with peptides with or without water. You can also apply different levels of coarse-graining to your system. You can use a classical forcefield or an NNP or use a combination. Could you describe the intended simulation setup in more detail?

**Comment by daniel1991zy** [comment]
> Hi. Generally, TorchMD can simulate the system with peptides with or without water. You can also apply different levels of coarse-graining to your system. You can use a classical forcefield or an NNP or use a combination. Could you describe the intended simulation setup in more detail?

As I know, TorchMD is suitable  for the systems which contains only one kind of protein(or peptide). In my simulation, the systems contains two different types of peptides, i.e., it's a mixture system of peptides. How can I to build such a CG-NNP?

**Comment by daniel1991zy** [comment]
I have send an issue to you, you mentioned that it needs some hacks, can you give me some detailed suggestions? 

> If you want to simulate multiple proteins in the same simulation box, torchMD can deal with that without an issue. The system is defined with a topology file and it can contain a single or multiple chains.
> 
> Simulation of multiple proteins in different replicas is currently not possible and, as Gianni mentioned, would require some hacks.
> 
> Can you describe in more detail on what you're trying to do so we can provide more feedback?

**Comment by MaciejMajew** [comment]
No hacks are needed. TorchMD can simulate such a system without any issue. The bonds between beads are defined in the topology file so multiple chains will need to be reflected there.

Do you already have an NNP trained for this system or do you need to train it?
